/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

/**
 *
 * @author ak200458
 */
public class equipmentList extends javax.swing.JFrame {

    /**
     * Creates new form equipmentList
     */
    public equipmentList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equipmentListPanel = new javax.swing.JPanel();
        equipmentListLabel = new javax.swing.JLabel();
        equipmentListBackButton = new javax.swing.JButton();
        equipmentListConfirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        equipmentListPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        equipmentListLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        equipmentListLabel.setText("Equipment List");

        equipmentListBackButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equipmentListBackButton.setText("Back");
        equipmentListBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentListBackButtonActionPerformed(evt);
            }
        });

        equipmentListConfirmButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equipmentListConfirmButton.setText("Confirm");
        equipmentListConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentListConfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout equipmentListPanelLayout = new javax.swing.GroupLayout(equipmentListPanel);
        equipmentListPanel.setLayout(equipmentListPanelLayout);
        equipmentListPanelLayout.setHorizontalGroup(
            equipmentListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipmentListPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(equipmentListLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(equipmentListPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(equipmentListBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(equipmentListConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        equipmentListPanelLayout.setVerticalGroup(
            equipmentListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipmentListPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(equipmentListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(equipmentListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipmentListBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipmentListConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(equipmentListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(equipmentListPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equipmentListBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentListBackButtonActionPerformed
        userMenu um = new userMenu();
        um.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_equipmentListBackButtonActionPerformed

    private void equipmentListConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentListConfirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentListConfirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(equipmentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(equipmentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(equipmentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(equipmentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new equipmentList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton equipmentListBackButton;
    private javax.swing.JButton equipmentListConfirmButton;
    private javax.swing.JLabel equipmentListLabel;
    private javax.swing.JPanel equipmentListPanel;
    // End of variables declaration//GEN-END:variables
}
