/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

/**
 *
 * @author ak200458
 */
public class giveUserAdmin extends javax.swing.JFrame {

    /**
     * Creates new form giveUserAdmin
     */
    public giveUserAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        giveUserAdminPanel = new javax.swing.JPanel();
        giveUserAdminLabel = new javax.swing.JLabel();
        usernameGiveUserAdminInput = new javax.swing.JTextField();
        confirmGiveUserAdminButton = new javax.swing.JButton();
        backButtonGiveUserAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        giveUserAdminPanel.setBackground(new java.awt.Color(204, 255, 204));
        giveUserAdminPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        giveUserAdminLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        giveUserAdminLabel.setText("Give User Admin");

        usernameGiveUserAdminInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameGiveUserAdminInput.setText("Username of User");
        usernameGiveUserAdminInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameGiveUserAdminInputActionPerformed(evt);
            }
        });

        confirmGiveUserAdminButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmGiveUserAdminButton.setText("Confirm");
        confirmGiveUserAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmGiveUserAdminButtonActionPerformed(evt);
            }
        });

        backButtonGiveUserAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backButtonGiveUserAdmin.setText("Back");
        backButtonGiveUserAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonGiveUserAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout giveUserAdminPanelLayout = new javax.swing.GroupLayout(giveUserAdminPanel);
        giveUserAdminPanel.setLayout(giveUserAdminPanelLayout);
        giveUserAdminPanelLayout.setHorizontalGroup(
            giveUserAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(giveUserAdminPanelLayout.createSequentialGroup()
                .addGroup(giveUserAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(giveUserAdminPanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(usernameGiveUserAdminInput, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(giveUserAdminPanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(backButtonGiveUserAdmin)
                        .addGap(63, 63, 63)
                        .addComponent(confirmGiveUserAdminButton))
                    .addGroup(giveUserAdminPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(giveUserAdminLabel)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        giveUserAdminPanelLayout.setVerticalGroup(
            giveUserAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(giveUserAdminPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(giveUserAdminLabel)
                .addGap(65, 65, 65)
                .addComponent(usernameGiveUserAdminInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(giveUserAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmGiveUserAdminButton)
                    .addComponent(backButtonGiveUserAdmin))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(giveUserAdminPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(giveUserAdminPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameGiveUserAdminInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameGiveUserAdminInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameGiveUserAdminInputActionPerformed

    private void backButtonGiveUserAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonGiveUserAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonGiveUserAdminActionPerformed

    private void confirmGiveUserAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmGiveUserAdminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmGiveUserAdminButtonActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giveUserAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giveUserAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giveUserAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giveUserAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giveUserAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtonGiveUserAdmin;
    private javax.swing.JButton confirmGiveUserAdminButton;
    private javax.swing.JLabel giveUserAdminLabel;
    private javax.swing.JPanel giveUserAdminPanel;
    private javax.swing.JTextField usernameGiveUserAdminInput;
    // End of variables declaration//GEN-END:variables
}
