/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

/**
 *
 * @author ak200458
 */
public class removeEquipment extends javax.swing.JFrame {

    /**
     * Creates new form removeEquipment
     */
    public removeEquipment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeEquipmentPanel = new javax.swing.JPanel();
        removeEquipmentLabel = new javax.swing.JLabel();
        removeEquipmentInput = new javax.swing.JTextField();
        backButtonRemoveEquipment = new javax.swing.JButton();
        confirmRemoveEquipmentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        removeEquipmentPanel.setBackground(new java.awt.Color(255, 204, 204));
        removeEquipmentPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        removeEquipmentLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        removeEquipmentLabel.setText("Remove Equipment");

        removeEquipmentInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeEquipmentInput.setText("Name Of Equipment");
        removeEquipmentInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEquipmentInputActionPerformed(evt);
            }
        });

        backButtonRemoveEquipment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backButtonRemoveEquipment.setText("Back");
        backButtonRemoveEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonRemoveEquipmentActionPerformed(evt);
            }
        });

        confirmRemoveEquipmentButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmRemoveEquipmentButton.setText("Confirm");
        confirmRemoveEquipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmRemoveEquipmentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeEquipmentPanelLayout = new javax.swing.GroupLayout(removeEquipmentPanel);
        removeEquipmentPanel.setLayout(removeEquipmentPanelLayout);
        removeEquipmentPanelLayout.setHorizontalGroup(
            removeEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeEquipmentPanelLayout.createSequentialGroup()
                .addGroup(removeEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeEquipmentPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(removeEquipmentInput, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removeEquipmentPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(removeEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(removeEquipmentPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(backButtonRemoveEquipment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmRemoveEquipmentButton))
                            .addComponent(removeEquipmentLabel))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        removeEquipmentPanelLayout.setVerticalGroup(
            removeEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeEquipmentPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(removeEquipmentLabel)
                .addGap(54, 54, 54)
                .addComponent(removeEquipmentInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(removeEquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButtonRemoveEquipment)
                    .addComponent(confirmRemoveEquipmentButton))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeEquipmentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeEquipmentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeEquipmentInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEquipmentInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeEquipmentInputActionPerformed

    private void backButtonRemoveEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonRemoveEquipmentActionPerformed
        adminMenu am = new adminMenu();
        am.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonRemoveEquipmentActionPerformed

    private void confirmRemoveEquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmRemoveEquipmentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmRemoveEquipmentButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(removeEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(removeEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(removeEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(removeEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new removeEquipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtonRemoveEquipment;
    private javax.swing.JButton confirmRemoveEquipmentButton;
    private javax.swing.JTextField removeEquipmentInput;
    private javax.swing.JLabel removeEquipmentLabel;
    private javax.swing.JPanel removeEquipmentPanel;
    // End of variables declaration//GEN-END:variables
}
