/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

/**
 *
 * @author ak200458
 */
public class removeUser extends javax.swing.JFrame {

    /**
     * Creates new form removeUser
     */
    public removeUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeUserPanel = new javax.swing.JPanel();
        removeUserLabel = new javax.swing.JLabel();
        removeUserUsernameInput = new javax.swing.JTextField();
        backButtonRemoveUser = new javax.swing.JButton();
        confirmRemoveUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        removeUserPanel.setBackground(new java.awt.Color(255, 204, 204));
        removeUserPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        removeUserLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        removeUserLabel.setText("Remove User");

        removeUserUsernameInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeUserUsernameInput.setText("Username of User");
        removeUserUsernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUserUsernameInputActionPerformed(evt);
            }
        });

        backButtonRemoveUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backButtonRemoveUser.setText("Back");
        backButtonRemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonRemoveUserActionPerformed(evt);
            }
        });

        confirmRemoveUserButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmRemoveUserButton.setText("Confirm");
        confirmRemoveUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmRemoveUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeUserPanelLayout = new javax.swing.GroupLayout(removeUserPanel);
        removeUserPanel.setLayout(removeUserPanelLayout);
        removeUserPanelLayout.setHorizontalGroup(
            removeUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeUserPanelLayout.createSequentialGroup()
                .addGroup(removeUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeUserPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(removeUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(removeUserLabel)
                            .addComponent(removeUserUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(removeUserPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(backButtonRemoveUser)
                        .addGap(42, 42, 42)
                        .addComponent(confirmRemoveUserButton)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        removeUserPanelLayout.setVerticalGroup(
            removeUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeUserPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(removeUserLabel)
                .addGap(59, 59, 59)
                .addComponent(removeUserUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(removeUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButtonRemoveUser)
                    .addComponent(confirmRemoveUserButton))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeUserPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeUserPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeUserUsernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeUserUsernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeUserUsernameInputActionPerformed

    private void backButtonRemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonRemoveUserActionPerformed
        adminMenu am = new adminMenu();
        am.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonRemoveUserActionPerformed

    private void confirmRemoveUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmRemoveUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmRemoveUserButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(removeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(removeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(removeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(removeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new removeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtonRemoveUser;
    private javax.swing.JButton confirmRemoveUserButton;
    private javax.swing.JLabel removeUserLabel;
    private javax.swing.JPanel removeUserPanel;
    private javax.swing.JTextField removeUserUsernameInput;
    // End of variables declaration//GEN-END:variables
}
