package GUIs;

/**
 *
 * @author ak200458
 */
public class userMenu extends javax.swing.JFrame {

    /**
     * Creates new form userMenu
     */
    public userMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userMenuPanel = new javax.swing.JPanel();
        closeProgramButtonUser = new javax.swing.JButton();
        yourCurrentBookingsButton = new javax.swing.JButton();
        yourBookingsHistory = new javax.swing.JButton();
        mainMenuLabel = new javax.swing.JLabel();
        rentEquipmentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userMenuPanel.setBackground(new java.awt.Color(255, 255, 204));
        userMenuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        closeProgramButtonUser.setText("Close Program");
        closeProgramButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeProgramButtonUserActionPerformed(evt);
            }
        });

        yourCurrentBookingsButton.setText("Your Current Bookings");
        yourCurrentBookingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourCurrentBookingsButtonActionPerformed(evt);
            }
        });

        yourBookingsHistory.setText("Your Booking History");
        yourBookingsHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourBookingsHistoryActionPerformed(evt);
            }
        });

        mainMenuLabel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        mainMenuLabel.setText("Main Menu");

        rentEquipmentButton.setText("Rent Equipment");
        rentEquipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentEquipmentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userMenuPanelLayout = new javax.swing.GroupLayout(userMenuPanel);
        userMenuPanel.setLayout(userMenuPanelLayout);
        userMenuPanelLayout.setHorizontalGroup(
            userMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMenuPanelLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(mainMenuLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(userMenuPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(userMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rentEquipmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(closeProgramButtonUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(userMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yourCurrentBookingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yourBookingsHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        userMenuPanelLayout.setVerticalGroup(
            userMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuLabel)
                .addGap(45, 45, 45)
                .addGroup(userMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yourCurrentBookingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeProgramButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(userMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yourBookingsHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentEquipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yourCurrentBookingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourCurrentBookingsButtonActionPerformed
        currentBookings curBook = new currentBookings();
        curBook.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_yourCurrentBookingsButtonActionPerformed

    private void yourBookingsHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourBookingsHistoryActionPerformed
        bookingHistory bookHist = new bookingHistory();
        bookHist.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_yourBookingsHistoryActionPerformed

    private void rentEquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentEquipmentButtonActionPerformed
        equipmentList equipList = new equipmentList();
        equipList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rentEquipmentButtonActionPerformed

    private void closeProgramButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeProgramButtonUserActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeProgramButtonUserActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userMenu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeProgramButtonUser;
    private javax.swing.JLabel mainMenuLabel;
    private javax.swing.JButton rentEquipmentButton;
    private javax.swing.JPanel userMenuPanel;
    private javax.swing.JButton yourBookingsHistory;
    private javax.swing.JButton yourCurrentBookingsButton;
    // End of variables declaration//GEN-END:variables

}
